"""
CEFR Question Banks — parallel structure for all supported languages.
"""
from typing import Dict, List
from models import CEFRQuestion, QuestionType


QUESTION_BANKS: Dict[str, List[CEFRQuestion]] = {
    "en": [
        CEFRQuestion(1, "A1", "Beginner", QuestionType.CONVERSATION,
            "Let's start simple! 😊\n\n**\"What's your name? Where are you from?\"**",
            "✅ **Great start!** You introduced yourself clearly.", 1),
        CEFRQuestion(2, "A1", "Beginner", QuestionType.CONVERSATION,
            "Nice to meet you! 🌟\n\n**\"How old are you? What is your job or what do you study?\"**",
            "✅ **Good!** You answered basic personal questions.", 1),
        CEFRQuestion(3, "A1+", "Beginner+", QuestionType.CONVERSATION,
            "Tell me about your family! 👨‍👩‍👧‍👦\n\n**\"How many people are in your family? What are their names?\"**",
            "✅ **Nice!** You described your family well.", 2),
        CEFRQuestion(4, "A1+", "Beginner+", QuestionType.SCENARIO,
            "You are at a restaurant. The waiter says:\n\n**\"Hello! What would you like to order?\"**\n\nWhat do you say?",
            "✅ **Good!** You used basic restaurant vocabulary.", 2,
            scenario_icon="🍔", scenario_title="Scenario: At the Restaurant",
            scenario_desc="You are at a restaurant and want to order food"),
        CEFRQuestion(5, "A2", "Elementary", QuestionType.CONVERSATION,
            "That sounds like a busy day! 💼\n\n**\"Tell me about your daily routine. What do you usually do in the morning?\"**",
            "✅ **Good!** You used simple present tense correctly.", 3),
        CEFRQuestion(6, "A2", "Elementary", QuestionType.IMAGE,
            "Look at this picture! 🏖️\n\n**\"Describe what you see. What do people usually do at the beach?\"**",
            "✅ **Nice!** You described a scene using present tense.", 3,
            image_emoji="🏖️"),
        CEFRQuestion(7, "A2", "Elementary", QuestionType.CONVERSATION,
            "Everyone has favorites! 🎵\n\n**\"What is your favorite food? Why do you like it?\"**",
            "✅ **Well done!** You expressed preferences with reasons.", 3),
        CEFRQuestion(8, "A2+", "Elementary+", QuestionType.SCENARIO,
            "You are shopping for a gift. The shop assistant asks:\n\n**\"Can I help you find something?\"**\n\nWhat do you say? Describe what you're looking for.",
            "✅ **Great!** You handled a shopping conversation well.", 4,
            scenario_icon="🛒", scenario_title="Scenario: Shopping",
            scenario_desc="You want to buy a gift for your friend"),
        CEFRQuestion(9, "B1", "Intermediate", QuestionType.CONVERSATION,
            "Interesting choice! 🎨\n\n**\"Describe your favorite hobby. Why do you enjoy it and how often do you do it?\"**",
            "✅ **Nice!** You expressed opinions and gave reasons.", 5),
        CEFRQuestion(10, "B1", "Intermediate", QuestionType.CONVERSATION,
            "Travel broadens the mind! ✈️\n\n**\"Tell me about a trip you took recently. Where did you go and what did you do?\"**",
            "✅ **Well done!** You used past tense to tell a story.", 5),
        CEFRQuestion(11, "B1", "Intermediate", QuestionType.IMAGE,
            "Look at this city! 🏙️\n\n**\"Describe this city. What do you think life is like there? Would you like to live there?\"**",
            "✅ **Excellent!** You gave opinions about a place with reasoning.", 5,
            image_emoji="🏙️"),
        CEFRQuestion(12, "B1", "Intermediate", QuestionType.CONVERSATION,
            "We all have dreams! 🌟\n\n**\"What are your plans for the next year? What would you like to achieve?\"**",
            "✅ **Great!** You talked about future plans using 'will' and 'would like'.", 5),
        CEFRQuestion(13, "B1+", "Intermediate+", QuestionType.CONVERSATION,
            "That's a thoughtful answer! 🏙️\n\n**\"If you could change one thing about your city, what would it be and why?\"**",
            "✅ **Excellent!** You used conditional sentences (would + verb).", 6),
        CEFRQuestion(14, "B1+", "Intermediate+", QuestionType.SCENARIO,
            "You missed your flight at the airport. You go to the airline desk and say:\n\n**\"I missed my flight to London. What should I do now?\"**\n\nThe agent asks: \"Do you have your ticket?\" What do you say?",
            "✅ **Impressive!** You handled a stressful situation calmly.", 6,
            scenario_icon="✈️", scenario_title="Scenario: At the Airport",
            scenario_desc="You missed your flight and need help"),
        CEFRQuestion(15, "B1+", "Intermediate+", QuestionType.CONVERSATION,
            "Technology is everywhere! 📱\n\n**\"Some people say technology makes us less social. Do you agree or disagree? Give examples.\"**",
            "✅ **Impressive!** You argued a point with supporting examples.", 6),
        CEFRQuestion(16, "B1+", "Intermediate+", QuestionType.IMAGE,
            "Look at this library! 📚\n\n**\"Some people prefer reading books, others prefer watching movies. Which do you prefer and why?\"**",
            "✅ **Great comparison!** You compared two things with clear reasons.", 6,
            image_emoji="📚"),
        CEFRQuestion(17, "B2", "Upper-Intermediate", QuestionType.CONVERSATION,
            "Life is full of tough choices! 🧭\n\n**\"Describe a difficult decision you had to make. How did you make it and what was the outcome?\"**",
            "✅ **Outstanding!** Complex narrative with cause and effect.", 7),
        CEFRQuestion(18, "B2", "Upper-Intermediate", QuestionType.SCENARIO,
            "You are in a job interview. The interviewer asks:\n\n**\"Tell me about a time you faced a challenge at work. How did you handle it?\"**\n\nGive a detailed answer using the STAR method (Situation, Task, Action, Result).",
            "🌟 **Outstanding!** You used the STAR method perfectly.", 7,
            scenario_icon="💼", scenario_title="Scenario: Job Interview",
            scenario_desc="You are in an interview for an important position"),
        CEFRQuestion(19, "B2", "Upper-Intermediate", QuestionType.CONVERSATION,
            "The world is changing! 🌍\n\n**\"What do you think is the biggest challenge facing your generation? How should we address it?\"**",
            "🌟 **Fantastic!** You discussed a complex issue with depth.", 7),
        CEFRQuestion(20, "B2+", "Upper-Intermediate+", QuestionType.CONVERSATION,
            "Wisdom comes with experience! 🦉\n\n**\"If you could give one piece of advice to your younger self, what would it be and why do you think it matters?\"**",
            "🌟 **Fantastic!** You reflected deeply and used advanced structures.", 8),
    ],
    "ru": [
        CEFRQuestion(1, "A1", "Начинающий", QuestionType.CONVERSATION,
            "Давайте начнём с простого! 😊\n\n**«Как вас зовут? Откуда вы?»**",
            "✅ **Отличное начало!** Вы чётко представились.", 1),
        CEFRQuestion(2, "A1", "Начинающий", QuestionType.CONVERSATION,
            "Рад познакомиться! 🌟\n\n**«Сколько вам лет? Кем вы работаете или чем учитесь?»**",
            "✅ **Хорошо!** Вы ответили на базовые вопросы о себе.", 1),
        CEFRQuestion(3, "A1+", "Начинающий+", QuestionType.CONVERSATION,
            "Расскажите о своей семье! 👨‍👩‍👧‍👦\n\n**«Сколько человек в вашей семье? Как их зовут?»**",
            "✅ **Отлично!** Вы хорошо описали свою семью.", 2),
        CEFRQuestion(4, "A1+", "Начинающий+", QuestionType.SCENARIO,
            "Вы в ресторане. Официант говорит:\n\n**«Здравствуйте! Что будете заказывать?»**\n\nЧто вы ответите?",
            "✅ **Хорошо!** Вы использовали базовый ресторанный словарь.", 2,
            scenario_icon="🍔", scenario_title="Сценарий: В ресторане",
            scenario_desc="Вы в ресторане и хотите заказать еду"),
        CEFRQuestion(5, "A2", "Элементарный", QuestionType.CONVERSATION,
            "Похоже, у вас насыщенный день! 💼\n\n**«Расскажите о вашем обычном дне. Что вы обычно делаете утром?»**",
            "✅ **Хорошо!** Вы правильно использовали настоящее время.", 3),
        CEFRQuestion(6, "A2", "Элементарный", QuestionType.IMAGE,
            "Посмотрите на эту картинку! 🏖️\n\n**«Опишите, что вы видите. Что люди обычно делают на пляже?»**",
            "✅ **Отлично!** Вы описали сцену, используя настоящее время.", 3,
            image_emoji="🏖️"),
        CEFRQuestion(7, "A2", "Элементарный", QuestionType.CONVERSATION,
            "У каждого есть любимое! 🎵\n\n**«Какая ваша любимая еда? Почему она вам нравится?»**",
            "✅ **Молодец!** Вы выразили предпочтения с объяснениями.", 3),
        CEFRQuestion(8, "A2+", "Элементарный+", QuestionType.SCENARIO,
            "Вы выбираете подарок. Продавец спрашивает:\n\n**«Чем могу помочь?»**\n\nЧто вы скажете? Опишите, что вы ищете.",
            "✅ **Отлично!** Вы справились с диалогом в магазине.", 4,
            scenario_icon="🛒", scenario_title="Сценарий: Покупки",
            scenario_desc="Вы хотите купить подарок другу"),
        CEFRQuestion(9, "B1", "Средний", QuestionType.CONVERSATION,
            "Интересный выбор! 🎨\n\n**«Опишите ваше любимое хобби. Почему вам это нравится и как часто вы этим занимаетесь?»**",
            "✅ **Отлично!** Вы выразили мнение и привели причины.", 5),
        CEFRQuestion(10, "B1", "Средний", QuestionType.CONVERSATION,
            "Путешествия расширяют кругозор! ✈️\n\n**«Расскажите о недавней поездке. Куда вы ездили и что делали?»**",
            "✅ **Молодец!** Вы использовали прошедшее время для рассказа.", 5),
        CEFRQuestion(11, "B1", "Средний", QuestionType.IMAGE,
            "Посмотрите на этот город! 🏙️\n\n**«Опишите этот город. Как вы думаете, какова там жизнь? Хотели бы вы там жить?»**",
            "✅ **Превосходно!** Вы высказали мнение о месте с аргументацией.", 5,
            image_emoji="🏙️"),
        CEFRQuestion(12, "B1", "Средний", QuestionType.CONVERSATION,
            "У всех есть мечты! 🌟\n\n**«Какие у вас планы на следующий год? Чего бы вы хотели достичь?»**",
            "✅ **Отлично!** Вы говорили о планах, используя будущее время.", 5),
        CEFRQuestion(13, "B1+", "Средний+", QuestionType.CONVERSATION,
            "Это продуманный ответ! 🏙️\n\n**«Если бы вы могли изменить одну вещь в вашем городе, что бы это было и почему?»**",
            "✅ **Превосходно!** Вы использовали условные предложения (бы + глагол).", 6),
        CEFRQuestion(14, "B1+", "Средний+", QuestionType.SCENARIO,
            "Вы опоздали на рейс. Подходите к стойке авиакомпании и говорите:\n\n**«Я опоздал на рейс в Лондон. Что мне теперь делать?»**\n\nАгент спрашивает: «У вас есть билет?» Что вы ответите?",
            "✅ **Впечатляет!** Вы спокойно справились со стрессовой ситуацией.", 6,
            scenario_icon="✈️", scenario_title="Сценарий: В аэропорту",
            scenario_desc="Вы опоздали на рейс и нуждаетесь в помощи"),
        CEFRQuestion(15, "B1+", "Средний+", QuestionType.CONVERSATION,
            "Технологии повсюду! 📱\n\n**«Некоторые говорят, что технологии делают нас менее социальными. Вы согласны или нет? Приведите примеры.»**",
            "✅ **Впечатляет!** Вы аргументировали свою точку зрения примерами.", 6),
        CEFRQuestion(16, "B1+", "Средний+", QuestionType.IMAGE,
            "Посмотрите на эту библиотеку! 📚\n\n**«Некоторые предпочитают читать книги, другие — смотреть фильмы. Что вы предпочитаете и почему?»**",
            "✅ **Отличное сравнение!** Вы сравнили две вещи с чёткими причинами.", 6,
            image_emoji="📚"),
        CEFRQuestion(17, "B2", "Выше среднего", QuestionType.CONVERSATION,
            "Жизнь полна трудных выборов! 🧭\n\n**«Опишите трудное решение, которое вам пришлось принять. Как вы его приняли и каков был результат?»**",
            "✅ **Выдающе!** Сложное повествование с причиной и следствием.", 7),
        CEFRQuestion(18, "B2", "Выше среднего", QuestionType.SCENARIO,
            "Вы на собеседовании. Интервьюер спрашивает:\n\n**«Расскажите о случае, когда вы столкнулись с трудностью на работе. Как вы с ней справились?»**\n\nДайте подробный ответ, используя метод STAR (Ситуация, Задача, Действие, Результат).",
            "🌟 **Выдающе!** Вы идеально применили метод STAR.", 7,
            scenario_icon="💼", scenario_title="Сценарий: Собеседование",
            scenario_desc="Вы на собеседовании на важную должность"),
        CEFRQuestion(19, "B2", "Выше среднего", QuestionType.CONVERSATION,
            "Мир меняется! 🌍\n\n**«Как вы думаете, каков самый большой вызов для вашего поколения? Как нам с ним справиться?»**",
            "🌟 **Фантастика!** Вы обсудили сложную проблему глубоко.", 7),
        CEFRQuestion(20, "B2+", "Выше среднего+", QuestionType.CONVERSATION,
            "Мудрость приходит с опытом! 🦉\n\n**«Если бы вы могли дать один совет своему молодому я, что бы это было и почему вы считаете это важным?»**",
            "🌟 **Фантастика!** Вы глубоко поразмыслили и использовали сложные конструкции.", 8),
    ]
}


def get_question_bank(lang: str) -> List[CEFRQuestion]:
    return QUESTION_BANKS.get(lang, QUESTION_BANKS["en"])
